# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-12 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


INITIAL_SO_VALUES = ['LOG', 'ALARM', 'CONTACTED', 'FIXED']
INITIAL_CRON_FUNCTION = ['crontab_monitor.crontabs.check_outside_web', ]

def forward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    for value in INITIAL_SO_VALUES:
        so = SelectOption(swarm='alert-log-status', value=value)
        so.save()

    for value in INITIAL_CRON_FUNCTION:
        cf_so = SelectOption(swarm='cron-function', value=value)
        cf_so.save()

    insp = Inspection(
        cron_format='#* * * * *',
        name="check_outside_web",
        function_option=cf_so,
        function_note="An example for showing a well cron function",
        kwargs='web_urls=https://www.google.com/|https://www.ho600.com/'
    )
    insp.save()


def backward(apps, schema_editor):
    SelectOption = apps.get_model('crontab_monitor', 'SelectOption')
    Inspection = apps.get_model('crontab_monitor', 'Inspection')
    sos = SelectOption.objects.filter(swarm='alert-log-status',
                                      value=INITIAL_SO_VALUES)
    sos.delete()

    insp = Inspection.objects.filter(name="check_outside_web",
                                  function_option__value__in=INITIAL_CRON_FUNCTION)
    insp.delete()

    cf_sos = SelectOption.objects.filter(swarm='cron-function', value__in=INITIAL_CRON_FUNCTION)
    cf_sos.delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('executed_end_time', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('executed_time_ymdhm', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('mail_body', models.TextField()),
                ('object_id_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_format', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=64)),
                ('function_note', models.TextField()),
                ('kwargs', models.CharField(max_length=255)),
            ],
            options={
                'permissions': (('view_inspection', 'View Inspection'), ('edit_inspection', 'Edit Inspection'), ('receive_notification_mail', 'Receive Notification Mail'), ('view_alert_log', 'View Alert Log'), ('edit_alert_log', 'Edit Alert Log')),
            },
        ),
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swarm', models.CharField(max_length=64, verbose_name='Swarm Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='selectoption',
            unique_together=set([('swarm', 'value')]),
        ),
        migrations.AddField(
            model_name='inspection',
            name='function_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crontab_monitor.SelectOption'),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crontab_monitor.Inspection'),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='objects_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='receivers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crontab_monitor.SelectOption'),
        ),
        migrations.RunPython(
            forward, backward
        ),
    ]
