# Generated by Django 2.1.14 on 2019-11-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'permissions': (('edit_inspection', 'Edit Inspection'), ('receive_notification_mail', 'Receive Notification Mail'), ('view_alert_log', 'View Alert Log'), ('edit_alert_log', 'Edit Alert Log'))},
        ),
    ]
