# Generated by Django 2.2.10 on 2020-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crontab_monitor', '0002_auto_20191120_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='kwargs',
            field=models.TextField(),
        ),
    ]
